### ISSUE TITLE
remove trailing whitespace from source code

### ISSUE THREAD

**Issue by mrothauer** [foodcoopshop/foodcoopshop#38]
the project's source code contains a lot of trailing whitespace which should be removed.

maybe there a git hooks that can be used - ideally integrated in github and not in the local git repository, so that it's guaranteed thet future commits do not add new trailing whitespace and everything is kept nice and clean :-)

**Comment by k-pd** [comment]
It's not possible to have hooks in GitHub. Not even in the payed version. And it's not possible to have git configured in a way, that cloning the repository sets up hooks (or anything else in `git config`). So there must be some extra steps described in the Developer area to setup the recommended git hooks. And hopefully someday there is something like developer-install scripts...

Across the internet there are some solutions for removing whitespace during commit. But there always is the same problem: this can lead to broken commits and lots of manual work. git itself also brings a [trailing whitespace pre-commit hook](https://www.kernel.org/pub/software/scm/git/docs/v1.6.1.3/githooks.html#_pre_commit) that could be used. But it also breaks the commit.

Instead of pre-commit hooks the solution could be: pre-push hooks. Meaning: You can do locally whatever You want, but before sending anything to GitHub Your changed files are verified against Coding Standards. By rejecting pushes You cannot end-up with a broken commit and prevent passing broken code. Sounds good to me. OK, there is no automagicically repaired files, but my editor does the trick, too.

There is a good collection of (possibly) useful hook scripts at [pre-commit by yelp](http://pre-commit.com/). This framework also supports "hooks during push" (see [Advanced Features](http://pre-commit.com/#advanced)). It is python based (which is fairly supported on all platforms) and relatively easy to set up. Having the FCS recommended config for that in the repository would be possible. And there are tons of other hooks available, not only trailing whitespace...

**Comment by k-pd** [comment]
OT: I miss a "development" (or similar) label to add to things like this.

**Comment by mrothauer** [comment]
thanks for the research. maybe adding the information in the developer settings is enough for the moment. i think, adding a section "developer settings" in the CONTRIBUTING.md would be the right place.

**Comment by mrothauer** [comment]
just added the info to CONTRIBUTING.md

**Comment by k-pd** [comment]
#41

**Comment by k-pd** [comment]
Solved by #55
