### ISSUE TITLE
Netzwerk-Modul - Produktdaten mit anderen FCS-Installationen synchronisieren

### ISSUE THREAD

**Issue by mrothauer** [foodcoopshop/foodcoopshop#68]

**Comment by k-pd** [comment]
I've been doing some brain squashing about this and similar features a while ago. I ended up with the thought, that this should be an optional module. And because of that in an additional repository. Here's why:

- This would allow adding more community networking features to the optional module without blowing up the basic functionality (and adding more weirdness to beginners trying to understand FoodCoopShop).
- Also, such a feature is a potential security / privacy risk, which may hinder some potential users from choosing FoodCoopShop.

**Comment by mrothauer** [comment]
good points, i'll think about packing everything in a cake plugin and create a new repo.

**Comment by mrothauer** [comment]
see https://github.com/foodcoopshop/fcs-network (not yet finished)

**Comment by mrothauer** [comment]
see https://github.com/foodcoopshop/fcs-network-plugin
